spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  datasource:
    url: jdbc:h2:tcp://localhost/~/greenroom
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging.level:
  #  org.hibernate.SQL: debug
  org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true
