spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  datasource:
    url: jdbc:h2:tcp://localhost/~/greenroom
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-key: AKIA5KTK6V24YGCLGFWH
      secret-key: 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
aws:
  s3:
    bucket: gr-dev-s3
    path:
      root: https://gr-dev-s3.s3.ap-northeast-2.amazonaws.com/
      plant: local/plant
  cdn:
    path:
      root: https://d3pfhbnnnj15dk.cloudfront.net/local/
      plant: local/plant

logging.level:
  #  org.hibernate.SQL: debug
  org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true