
## 추후 환경마다 oauth 를 분리해야 함.

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(be1IU8EoVx5ZWFPjfv74bsoGBGcqx6OUssHAuqqLPCWuC3rkSJpUorMv8vXGkJBEQQprC53y+Y4BNVlVV3d08qab1ypBFVZV9VadlrS4pPWdW1YAgjSCsQ==)
            client-secret: ENC(kvsCwsdKKsQIUZ1DVSCxQM2xSFPLjcNICkinRq4erVw26SZsLq9IwrWMr7sx1Xso)
            redirect-uri: ENC(E98H1p4xx35zyOAmhwWbVQV/K6KfNyhBDBWQ/4TRih8n8O1ghevBsNzDaGPqITOZiCvChD0rI6c=)
            scope: profile,email
